# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

c1 = Course.create( name: "Science 2")
c2 = Course.create( name: 'Mathematics')

u1 = User.create( name: 'Instructor1', email: 'ins1@email.com', role: 'instructor')
u2 = User.create( name: 'Instructor2', email: 'ins2@email.com', role: 'instructor')
u3 = User.create( name: 'Student1', email: 'student1@email.com', role: 'student')
u4 = User.create( name: 'Student2', email: 'student2@email.com', role: 'student')
u5 = User.create( name: 'Student3', email: 'student3@email.com', role: 'student')
u6 = User.create( name: 'Student4', email: 'student4@email.com', role: 'student')
u7 = User.create( name: 'Student5', email: 'student5@email.com', role: 'student')
u8 = User.create( name: 'Student6', email: 'student6@email.com', role: 'student')
u9 = User.create( name: 'Student7', email: 'student7@email.com', role: 'student')
u10 = User.create( name: 'Student8', email: 'student8@email.com', role: 'student')
u11 = User.create( name: 'Student9', email: 'student9@email.com', role: 'student')
u12 = User.create( name: 'Student10', email: 'student10@email.com', role: 'student')

b1 = Book.create(title: 'Science book', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ')
b2 = Book.create( title: 'Math book', content: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.')

e1 = Enrollment.create( user_id: u1.id, course_id: c1.id )
e2 = Enrollment.create( user_id: u2.id, course_id: c2.id )
e3 = Enrollment.create( user_id: u3.id, course_id: c1.id )
e4 = Enrollment.create( user_id: u4.id, course_id: c1.id )
e5 = Enrollment.create( user_id: u5.id, course_id: c2.id )
e6 = Enrollment.create( user_id: u6.id, course_id: c2.id )
e7 = Enrollment.create( user_id: u7.id, course_id: c2.id )
e8 = Enrollment.create( user_id: u8.id, course_id: c2.id )
e9 = Enrollment.create( user_id: u9.id, course_id: c2.id )
e10 = Enrollment.create( user_id: u10.id, course_id: c2.id )
e11 = Enrollment.create( user_id: u11.id, course_id: c2.id )
e12 = Enrollment.create( user_id: u12.id, course_id: c2.id )
e18 = Enrollment.create( user_id: u5.id, course_id: c1.id )
e19 = Enrollment.create( user_id: u6.id, course_id: c1.id )
e20 = Enrollment.create( user_id: u7.id, course_id: c1.id )
e21 = Enrollment.create( user_id: u8.id, course_id: c1.id )
e22 = Enrollment.create( user_id: u9.id, course_id: c1.id )

r1 = Readingtime.create( user_id: u3.id, book_id: b1.id, time: '1h 45min') 
r2 = Readingtime.create( user_id: u4.id, book_id: b1.id, time: '2h 30min') 
r3 = Readingtime.create( user_id: u5.id, book_id: b2.id, time: '1h 30min') 
r4 = Readingtime.create( user_id: u6.id, book_id: b2.id, time: '3h 40min') 
r5 = Readingtime.create( user_id: u7.id, book_id: b2.id, time: '2h 20min') 
r6 = Readingtime.create( user_id: u8.id, book_id: b2.id, time: '2h 40min') 
r7 = Readingtime.create( user_id: u9.id, book_id: b2.id, time: '1h 30min') 
r8 = Readingtime.create( user_id: u10.id, book_id: b2.id, time: '1h 15min') 
r9 = Readingtime.create( user_id: u11.id, book_id: b2.id, time: '2h 40min') 
r10 = Readingtime.create( user_id: u12.id, book_id: b2.id, time: '8h 50min')
r16 = Readingtime.create( user_id: u6.id, book_id: b1.id, time: '4h 40min') 
r17 = Readingtime.create( user_id: u7.id, book_id: b1.id, time: '1h 20min') 
r18 = Readingtime.create( user_id: u8.id, book_id: b1.id, time: '1h 10min')
